In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.Collecting numpy
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 540.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 991.0 kB/s eta 0:00:16
   ---------------------------------------- 0.1/15.8 MB 1.2 MB/s eta 0:00:14
   ---------------------------------------- 0.2/15.8 MB 1.5 MB/s eta 0:00:11
   ---------------------------------------- 0.2/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.4/15.8 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.6/15.8 MB 2.2 MB/s eta 0:00:07
   - -------------------------------------- 0.7/15.8 MB 2.3 MB/s eta 0:0

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [3]:
python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax (842801469.py, line 1)

In [4]:
pip install numpy


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
random_int_array = np.random.randint(1, 50, size=10)
random_int_array

array([31, 24, 43, 27, 40, 44,  3,  2, 14, 36])

In [7]:
np.mean(random_int_array)

26.4

In [9]:
a = np.random.randint(1, 50, size=(3,3))
b = np.random.randint(1, 50, size=(3,3))
c=a+b
c


array([[29, 79, 72],
       [83, 43, 44],
       [74, 24, 61]])

In [10]:
np.mean(c)

56.55555555555556

In [12]:
random_int_array = np.random.randint(1, 100, size=20)
condition=random_int_array>50
random_int_array=random_int_array[condition]
random_int_array

array([76, 57, 88, 63, 65, 72, 91, 76, 65, 65])

In [15]:
arr = np.random.randint(1, 10, size=10)
arr

array([5, 3, 4, 6, 8, 5, 9, 6, 9, 3, 8, 7, 2, 3, 1, 3, 4, 3, 3, 2])

In [16]:
np.random.shuffle(arr)
arr

array([3, 6, 9, 3, 3, 5, 8, 7, 5, 9, 4, 2, 4, 3, 1, 3, 8, 3, 6, 2])

In [18]:
randomindex=np.random.randint(0,10)
x=arr[randomindex]
x



9